project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "qmd/*.qmd"

website:
  title: "Analyse exploratoire de la réussite scolaire"
  site-url: "https://mohamedazizsassi.github.io/Analyse-exploratoire-avec-R/"
  repo-url: "https://github.com/mohamedazizsassi/Analyse-exploratoire-avec-R"
  
  repo-actions: [edit, issue]
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: Projects
        contents:
          - qmd/student-performance-eda.qmd
format:
  html:
    theme: light
    css: thpe.css
    toc: true
    number-sections: true
    code-fold: true
    code-summary: "Show code"
    code-link: true
    code-overflow: scroll

# Configuration WebR (R seulement)
webr:
  packages: ["dplyr", "ggplot2", "readxl", "tidyr", "lubridate", "car", "lmtest"]

execute:
  freeze: true
  cache: false
  echo: true
  warning: false
  message: false
  engine: r  # ← FORCER l'utilisation de R seulement

# DÉSACTIVER Jupyter
kernel:
  jupyter: false

bibliography: bib.bib
csl: apa.csl
